### ISSUE TITLE
Nice mod, will it be updated to higher MC edition?

### ISSUE THREAD

**Issue by ZYLHL** [Hemogoblins/BetterRecords#118]
BetterRecords is wonderful ,cause I can build a truly night bar in Minecraft, and listen every my favorite music.
I wanna know if BetterRecords will come out on higher Minecraft edition, for example, 1.16 or 1.17(which will be ready this summer or autumn). I also want to use Record Player in some 1.16's modpacks(AOF3, Valhelsia 3 etc.)

And if there have possibility, I also want a Fabric edition.:)

**Comment by NicholasFeldman** [comment]
Yes, currently a version for 1.16.4 is in development. I'm building it out as a full 2.0 version, with a bunch of new features and bugfixes and such. As of now I don't have an ETA, but it _is_ in the works.

As for Fabric, no. I very strongly dislike Fabric, and don't have enough free time as it is to maintain a second version for an inferior modloader with less users.
